FROM python:latest

RUN \
pip install flask-mysqldb mysql-connector-python && \
mkdir -p /srv/templates

COPY ./app_1.py /srv
COPY ./index.html /srv/templates

CMD ["flask","--app","/srv/app_1","run","--host=0.0.0.0"]
